apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yb5ck4m4n-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yb5ck4m4n-go 
  name: yb5ck4m4n-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yb5ck4m4n-go 
